version: "3"
services:
  backend:
    container_name: strapi
    image: pgphotographie/app:backend-latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "1337:1337"
    networks:
      - strapi
  frontend:
    container_name: frontend
    image: pgphotographie/app:frontend-latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    networks:
      - strapi
    volumes:
      - /etc/letsencrypt/:/etc/letsencrypt/

networks:
  strapi:
    name: Strapi
