version: "3"
services:
  strapi:
    container_name: strapi
    image: pgphotographie/app:backend-latest
    pull_policy: always
    restart: unless-stopped
    ports:
      - "1337:1337"
    networks:
      - strapi

networks:
  strapi:
    name: Strapi
    driver: bridge
